spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.206.128:3306/springboot?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jpa:
    show-sql: true
server:
   context-path: /sell
   port: 8080

weChat:
 myAppId: wx3c64c76a13e70aaf
 myAppSecret: c5e7f39c0f35826f030dff6ad35c5499

 # mybatis
mybatis:
        typeAliasesPackage: com.astro.repository
        configuration:
                    map-underscore-to-camel-case: true
                    default-fetch-size: 100
                    default-statement-timeout: 3000