spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.206.128:3306/springboot?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: root
    #password: 123456
    password:
  jpa:
    show-sql: true
server:
  context-path: /sell